pipeline {
    agent { label 'tableau-schema-migration-node' }

    environment {
        AWS_REGION = 'us-east-1'
        ACCOUNT_ID = '180350466832'
        REPO_NAME  = 'tableau-schema-migration'
        REGISTRY   = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
        ECR_REPO   = "${REGISTRY}/${REPO_NAME}"
    }

    stages {
        stage('Checkout') {
            steps { checkout scm }
        }

        stage('Build Docker Image') {
            steps {
               
                sh 'docker build -t ${ECR_REPO}:latest -f deploy/Dockerfile .'
            }
        }

        stage('Login to AWS ECR') {
            steps {
                sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${REGISTRY}"
            }
        }

        stage('Push Docker Image') {
            steps {
                sh "docker push ${ECR_REPO}:latest"
            }
        }
    }
}
