pipeline {
    agent { label 'tableau-schema-migration-node' }

    environment {
        AWS_REGION = 'us-east-1'
        ECR_REPO = '180350466832.dkr.ecr.us-east-1.amazonaws.com/tableau-schema-migration'
        IMAGE_NAME = 'tableau-schema-migration'
    }

    stages {
        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${IMAGE_NAME} -f deploy/Dockerfile ."
                sh "docker tag ${IMAGE_NAME}:latest ${ECR_REPO}:latest"
            }
        }

        stage('Login to AWS ECR') {
            steps {
                sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REPO}"
            }
        }

        stage('Push Docker Image') {
            steps {
                sh "docker push ${ECR_REPO}:latest"
            }
        }
    }
}
