pipeline {
    agent any
    environment {
        AWS_REGION = 'us-east-1'
    }
    
        stage('Run All JSONs with AWS Credentials') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'AWS-Credentials-PRODUS',
                        usernameVariable: 'AWS_ACCESS_KEY_ID',
                        passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                    )
                ]) {
                    sh '''
                    export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
                    export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

                    # Since this Jenkinsfile is in US_PROD_Schema/, we need to go one level up
                    cd ..
                    python3 run_all_json_folder.py
                    '''
                }
            }
        }
    }
    post {
        always {
            echo 'Finished.'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}
